# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cyber Threat Intelligence Technical Committee
description: > # this means to ignore newlines until "baseurl:"
  The OASIS Cyber Threat Intelligence (CTI) TC supports automated information
  sharing for cybersecurity situational awareness, real-time network defense,
  and sophisticated threat analysis.
baseurl: "/cti-documentation" # the subpath of your site, e.g. /blog
url: "https://oasis-open.github.io" # the base hostname & protocol for your site
last_updated: "Tue Sep 12 17:12:27 UTC 2017" # Should be changed whenever a new commit is made to master. 
                                             # Currently is manual with `date -u` used for UTC
copyright: "Copyright &copy; 2016, OASIS Open"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  smart_quotes:  ["apos", "apos", "ldquo", "rdquo"]
