# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: cti-documentation test harness
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    name: Python 3.x Build
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and update essential dependencies
      run: |
        pip install -U pip setuptools
        pip install stix2-validator
    - name: Validate Examples
      run: |
        ./validate-examples.sh
